query {
  advisorsPage {
    data {
      attributes {
        banner {
          data {
            attributes {
              cssClass
              title
              content
              background {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
        menu {
          data {
            attributes {
              links {
                title
                href
              }
            }
          }
        }
        peopleSection {
          data {
            attributes {
              title
              people(pagination: { limit: 100 }) {
                data {
                  attributes {
                    name
                    education
                    designation
                    image {
                      data {
                        attributes {
                          url
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
