query {
  careersPage {
    data {
      attributes {
        banner {
          data {
            attributes {
              cssClass
              title
              content
              background {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }

        menu {
          data {
            attributes {
              links {
                title
                href
              }
            }
          }
        }

        menuTitle
      }
    }
  }
}
