query {
  companiesPages(filters: { slug: { eq: "%s" } }, pagination: { limit: 1 }) {
    data {
      attributes {
        content
        slug
        companySections {
          data {
            attributes {
              companies(pagination: { limit: 100 }) {
                data {
                  attributes {
                    name
                    href
                    description
                    image {
                      data {
                        attributes {
                          url
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
