query {
  footer {
    data {
      attributes {
        menus {
          data {
            attributes {
              links {
                href
                title
                isExternal
              }
              image {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
        background {
          data {
            attributes {
              url
            }
          }
        }
        address
        newsLetter {
          placeholder
          buttonText
          title
          subtitle
        }
      }
    }
  }
}
