query {
  header {
    data {
      attributes {
        menu {
          data {
            attributes {
              links {
                href
                title
              }
              image {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}