query {
  header {
    data {
      attributes {
        menu {
          data {
            attributes {
              links {
                href
                title
                isExternal
              }
              image {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
        notificationBar {
          content
          show
        }
      }
    }
  }
}
