query home {
  index {
    data {
      attributes {
        mainBanner {
          data {
            attributes {
              title
              link {
                text
                href
              }
              video {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
        about {
          data {
            attributes {
              title
              content
              image {
                data {
                  attributes {
                    url
                  }
                }
              }
              background {
                data {
                  attributes {
                    url
                  }
                }
              }
              button {
                text
                href
              }
            }
          }
        }
        companySection {
          data {
            attributes {
              title
              content
              button {
                text
                href
              }
              companies {
                data {
                  attributes {
                    name
                    href
                    description
                    image {
                      data {
                        attributes {
                          url
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        banner {
          data {
            attributes {
              title
              background {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
        storySection {
          data {
            attributes {
              title
              description
              moreButton {
                text
                href
              }
              stories(pagination: { limit: 2 }) {
                data {
                  attributes {
                    title
                    eventDate
                    image {
                      data {
                        attributes {
                          url
                        }
                      }
                    }
                    href
                    type
                  }
                }
              }
            }
          }
        }
        sponsors {
          data {
            attributes {
              logos {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
