query {
  processPage {
    data {
      attributes {
        banner {
          data {
            attributes {
              title
              cssClass
              content
              background {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
        processes {
          data {
            attributes {
              title
              content
            }
          }
        }
      }
    }
  }
}
