query {
  storiesPage {
    data {
      attributes {
        banner {
          data {
            attributes {
              cssClass
              title
              content
              background {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }

        stories(pagination: { limit: 10 }) {
          data {
            attributes {
              title
              type
              href
              eventDate
              image {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
