query {
  storiesPage {
    data {
      attributes {
        banner {
          data {
            attributes {
              title
              content
              background {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
        
        stories(pagination: {limit: 10}) {
          data {
            attributes {
              title
              type
              href
              image {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}